### ISSUE TITLE
March 2022 direct download links

### ISSUE THREAD

**Issue by a-raccoon** [pinkflames/fluid-soundfont#1]
I found a direct download link that works.  This is the identical Fluid soundfont in this distro, as from Debian/Ubuntu/Gentoo.  The referenced musescore link (http://prereleases.musescore.org/soundfont/fluid-soundfont_3.1.tar.gz) is now dead.

https://keymusician01.s3.amazonaws.com/FluidR3_GM.zip
ref: https://member.keymusician.com/Member/FluidR3_GM/index.html

file: FluidR3_GM.sf2
bytes: 148398306
sha512: 023cca1683ae18376999ae8121fbfbd134f345b6539e32b2eaa91929e23695785798e9983aaa1bb1e2c88587c8d5b172e4a041b505fff3fbd8bd17314cb8c4e3

---

Here is the modified musescore version of this soundfont.  This is not the same soundfont in this distro, but the newer revision.  Their old link (https://musescore.org/download/fluid-soundfont.tar.gz) is now dead.

FluidR3 GM2-2 Soundfont Changes Log
20/06/13 - v2.2 - Church Organist Missing note (#94) added to Violin, and range extended to G7 (MIDI#103) for compatibility with MuseScore 2

http://ftp.osuosl.org/pub/musescore/soundfont/
http://ftp.osuosl.org/pub/musescore/soundfont/fluid-soundfont.tar.gz
http://ftp.osuosl.org/pub/musescore/soundfont/fluid-soundfont.zip

file: FluidR3 GM2-2.SF2
bytes: 148,345,256
sha512: 5526c2e41f99a3f9b251db72b0bded0a43e0c4a8a0f0b29983c76fad69c3de31186686fb26bab5a08c32d4986f552278a90710d94f66da64da19055cfbc8c3f3

**Comment by pinkflames** [comment]
Hi, the point of the download links was to document where the these files originate from. While it's nice to know that there's direct download links that someone could use, ultimately that's not what this repository was created for, which is to provide an archival copy hosted by GitHub and indirectly Microsoft.

As for calling the current MuseScore download a version, I, like probably many GNU/Linux distros, would argue that it's a derivative work by no doubt skill people but it's nevertheless a derivative, so it can't be considered a newer version of the same thing. Meaning it should be called something unambiguously different.

This is the same reason why I have not tagged a release for this repository, because I do not believe I have the right to issue any releases of the Fluid soundfont.

I'll leave the issue open for now, because I'm not sure what to do about it but I hope my answer has clarified at least some parts of what you wanted.

**Comment by a-raccoon** [comment]
All fair points.  I felt compelled to mention it to aid with continuity of the documentation, but also to include the version notes provided in their so-called version 2.2 which express one "fix" and an "added."  I'm sure someone better skilled at soundfonts can independently identify that "version 1" has a missing note #94 for Violin.

**Comment by pinkflames** [comment]
I'm not contesting that MuseScore forks (at least their initial releases) are almost certainly an improvement over the original. However I created this repository because I felt that it was improper and disingenuous to lose the history of an important open source/free software dataset due to a controversial open source project.

I did also consider including the modified soundfont but decided against it, because I do not want to have anything to do with the Muse group and their UK lawyers or Russian owners.

I think this issue has run its course, so I'll close it now. If you think there's something more to be done, feel free to re-open this one or file a new one (not sure if GitHub allows the original reporter to re-open a closed issue).
